//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities.Relacional
{
    using Domain.Core;
    using System;
    using System.Collections.Generic;
    
    public partial class Exercicio : BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exercicio()
        {
            this.UsuarioExercicio = new HashSet<UsuarioExercicio>();
        }
    
        public int Id { get; set; }
        public int IdBloco { get; set; }
        public string Pergunta { get; set; }
        public string Gabarito { get; set; }
        public int Ordem { get; set; }
    
        public virtual Bloco Bloco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioExercicio> UsuarioExercicio { get; set; }
    }
}
