//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities.Relacional
{
    using Domain.Core;
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioProvaQuestao : BaseEntity
    {
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public int IdMatricula { get; set; }
        public int IdQuestao { get; set; }
        public System.DateTime DataInicio { get; set; }
        public string Pergunta { get; set; }
        public string Resposta { get; set; }
        public bool Acerto { get; set; }
        public string ObsCorrecao { get; set; }
        public string Gabarito { get; set; }
    
        public virtual Matricula Matricula { get; set; }
        public virtual Questao Questao { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
