//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities.Relacional
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoccoWebApiClienteProduto
    {
        public long Id { get; set; }
        public int IdProduto { get; set; }
        public string CodigoProduto { get; set; }
        public int CodigoCliente { get; set; }
        public bool Ativo { get; set; }
    }
}
