//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities.Relacional
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoccoWebApiConfiguracao
    {
        public int Id { get; set; }
        public string ApiClientId { get; set; }
        public string ApiUser { get; set; }
        public string ApiPassword { get; set; }
        public bool ApiKillOtherSessions { get; set; }
        public string ApiBaseUrl { get; set; }
    }
}
