//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Diagram
{
    using Domain.Entities.Relacional;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrincipalDBContainer : DbContext
    {
        public PrincipalDBContainer()
            : base("name=PrincipalDBContainer")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academia> Academia { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<AreaCurso> AreaCurso { get; set; }
        public virtual DbSet<Banner> Banner { get; set; }
        public virtual DbSet<Bloco> Bloco { get; set; }
        public virtual DbSet<Codigo> Codigo { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Exercicio> Exercicio { get; set; }
        public virtual DbSet<Faq> Faq { get; set; }
        public virtual DbSet<Matricula> Matricula { get; set; }
        public virtual DbSet<Modulo> Modulo { get; set; }
        public virtual DbSet<Questao> Questao { get; set; }
        public virtual DbSet<Recurso> Recurso { get; set; }
        public virtual DbSet<Testemunho> Testemunho { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioBloco> UsuarioBloco { get; set; }
        public virtual DbSet<UsuarioExercicio> UsuarioExercicio { get; set; }
        public virtual DbSet<UsuarioProvaQuestao> UsuarioProvaQuestao { get; set; }
    }
}
