//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academia
    {
        public Academia()
        {
            this.Banner = new HashSet<Banner>();
            this.Curso = new HashSet<Curso>();
            this.Evento = new HashSet<Evento>();
            this.Faq = new HashSet<Faq>();
            this.Testemunho = new HashSet<Testemunho>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string Email { get; set; }
        public string SenhaEmail { get; set; }
        public string Smtp { get; set; }
        public int SmtpPorta { get; set; }
        public string UrlBase { get; set; }
        public string Url { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaRobots { get; set; }
        public string MetaGoogleBot { get; set; }
        public string MetaGenerator { get; set; }
        public string MetaRevisiteAfter { get; set; }
        public string Cnpj { get; set; }
        public string Telefone { get; set; }
        public string Endereco { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Uf { get; set; }
        public string Cep { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public bool Ativo { get; set; }
    
        public virtual ICollection<Banner> Banner { get; set; }
        public virtual ICollection<Curso> Curso { get; set; }
        public virtual ICollection<Evento> Evento { get; set; }
        public virtual ICollection<Faq> Faq { get; set; }
        public virtual ICollection<Testemunho> Testemunho { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
