//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACAD_USUARIOS_BLOCOS
    {
        public long CD_USUARIO_BLOCO { get; set; }
        public long CD_USUARIO { get; set; }
        public long CD_BLOCO { get; set; }
    
        public virtual ACAD_BLOCOS ACAD_BLOCOS { get; set; }
        public virtual ACAD_USUARIOS ACAD_USUARIOS { get; set; }
    }
}
