//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACAD_ACADEMIAS
    {
        public ACAD_ACADEMIAS()
        {
            this.ACAD_BANNERS = new HashSet<ACAD_BANNERS>();
            this.ACAD_CURSOS = new HashSet<ACAD_CURSOS>();
            this.ACAD_EVENTOS = new HashSet<ACAD_EVENTOS>();
            this.ACAD_FAQS = new HashSet<ACAD_FAQS>();
            this.ACAD_TESTEMUNHOS = new HashSet<ACAD_TESTEMUNHOS>();
            this.ACAD_USUARIOS = new HashSet<ACAD_USUARIOS>();
        }
    
        public long CD_ACADEMIA { get; set; }
        public string NM_ACADEMIA { get; set; }
        public string TX_DESCRICAO { get; set; }
        public string TX_EMAIL { get; set; }
        public string TX_SENHA_EMAIL { get; set; }
        public string TX_SMTP { get; set; }
        public int TX_SMTP_PORTA { get; set; }
        public string TX_URL_BASE { get; set; }
        public string TX_URL { get; set; }
        public string TX_META_DESCRIPTION { get; set; }
        public string TX_META_KEYWORDS { get; set; }
        public string TX_META_ROBOTS { get; set; }
        public string TX_META_GOOGLEBOT { get; set; }
        public string TX_META_GENERATOR { get; set; }
        public string TX_META_REVISITE_AFTER { get; set; }
        public string TX_CNPJ { get; set; }
        public string TX_TEL { get; set; }
        public string TX_ENDERECO { get; set; }
        public string TX_NUMERO { get; set; }
        public string TX_COMPLEMENTO { get; set; }
        public string TX_BAIRRO { get; set; }
        public string TX_CIDADE { get; set; }
        public string TX_ESTADO { get; set; }
        public string TX_CEP { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public bool FL_ATIVO { get; set; }
    
        public virtual ICollection<ACAD_BANNERS> ACAD_BANNERS { get; set; }
        public virtual ICollection<ACAD_CURSOS> ACAD_CURSOS { get; set; }
        public virtual ICollection<ACAD_EVENTOS> ACAD_EVENTOS { get; set; }
        public virtual ICollection<ACAD_FAQS> ACAD_FAQS { get; set; }
        public virtual ICollection<ACAD_TESTEMUNHOS> ACAD_TESTEMUNHOS { get; set; }
        public virtual ICollection<ACAD_USUARIOS> ACAD_USUARIOS { get; set; }
    }
}
