//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACAD_EVENTOS
    {
        public long CD_EVENTO { get; set; }
        public long CD_ACADEMIA { get; set; }
        public string NM_EVENTO { get; set; }
        public System.DateTime DT_INICIO { get; set; }
        public Nullable<System.DateTime> DT_FINAL { get; set; }
        public string TX_URL { get; set; }
        public string TX_DESCRICAO { get; set; }
        public System.DateTime DT_DATA { get; set; }
        public bool FL_ATIVO { get; set; }
    
        public virtual ACAD_ACADEMIAS ACAD_ACADEMIAS { get; set; }
    }
}
