//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACAD_BLOCOS
    {
        public ACAD_BLOCOS()
        {
            this.ACAD_EXERCICIOS = new HashSet<ACAD_EXERCICIOS>();
            this.ACAD_USUARIOS_BLOCOS = new HashSet<ACAD_USUARIOS_BLOCOS>();
        }
    
        public long CD_BLOCO { get; set; }
        public long CD_MODULO { get; set; }
        public string NM_BLOCO { get; set; }
        public string NM_PAGE { get; set; }
        public int NR_ORDEM { get; set; }
    
        public virtual ACAD_MODULOS ACAD_MODULOS { get; set; }
        public virtual ICollection<ACAD_EXERCICIOS> ACAD_EXERCICIOS { get; set; }
        public virtual ICollection<ACAD_USUARIOS_BLOCOS> ACAD_USUARIOS_BLOCOS { get; set; }
    }
}
