//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACAD_FAQS
    {
        public long CD_FAQ { get; set; }
        public long CD_ACADEMIA { get; set; }
        public string TX_PERGUNTA { get; set; }
        public string TX_RESPOSTA { get; set; }
        public int NR_ORDEM { get; set; }
    
        public virtual ACAD_ACADEMIAS ACAD_ACADEMIAS { get; set; }
    }
}
