//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACAD_RECURSOS
    {
        public long CD_RECURSO { get; set; }
        public long CD_MODULO { get; set; }
        public string NM_RECURSO { get; set; }
        public string NM_PAGE { get; set; }
    
        public virtual ACAD_MODULOS ACAD_MODULOS { get; set; }
    }
}
