//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACAD_CODIGOS
    {
        public System.Guid CD_CODIGO { get; set; }
        public long CD_CURSO { get; set; }
        public Nullable<System.DateTime> DT_DATA { get; set; }
        public bool FL_ATIVO { get; set; }
    
        public virtual ACAD_CURSOS ACAD_CURSOS { get; set; }
    }
}
