//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACAD_AREAS
    {
        public ACAD_AREAS()
        {
            this.ACAD_AREAS_CURSOS = new HashSet<ACAD_AREAS_CURSOS>();
        }
    
        public int CD_AREA { get; set; }
        public string NM_AREA { get; set; }
    
        public virtual ICollection<ACAD_AREAS_CURSOS> ACAD_AREAS_CURSOS { get; set; }
    }
}
