//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACAD_CURSOS
    {
        public ACAD_CURSOS()
        {
            this.ACAD_AREAS_CURSOS = new HashSet<ACAD_AREAS_CURSOS>();
            this.ACAD_CODIGOS = new HashSet<ACAD_CODIGOS>();
            this.ACAD_MATRICULAS = new HashSet<ACAD_MATRICULAS>();
            this.ACAD_MODULOS = new HashSet<ACAD_MODULOS>();
        }
    
        public long CD_CURSO { get; set; }
        public long CD_ACADEMIA { get; set; }
        public long CD_PROFESSOR { get; set; }
        public string NM_CURSO { get; set; }
        public string TX_RESUMO { get; set; }
        public string TX_DESCRICAO { get; set; }
        public string TX_EMAIL { get; set; }
        public string TX_MOEDA { get; set; }
        public decimal VL_CURSO { get; set; }
        public System.DateTime DT_DATA { get; set; }
        public bool FL_ATIVO { get; set; }
        public int NR_ORDEM { get; set; }
    
        public virtual ACAD_ACADEMIAS ACAD_ACADEMIAS { get; set; }
        public virtual ICollection<ACAD_AREAS_CURSOS> ACAD_AREAS_CURSOS { get; set; }
        public virtual ICollection<ACAD_CODIGOS> ACAD_CODIGOS { get; set; }
        public virtual ACAD_USUARIOS ACAD_USUARIOS { get; set; }
        public virtual ICollection<ACAD_MATRICULAS> ACAD_MATRICULAS { get; set; }
        public virtual ICollection<ACAD_MODULOS> ACAD_MODULOS { get; set; }
    }
}
