//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACAD_EXERCICIOS
    {
        public ACAD_EXERCICIOS()
        {
            this.ACAD_USUARIOS_EXERCICIOS = new HashSet<ACAD_USUARIOS_EXERCICIOS>();
        }
    
        public long CD_EXERCICIO { get; set; }
        public long CD_BLOCO { get; set; }
        public string TX_PERGUNTA { get; set; }
        public string TX_GABARITO { get; set; }
        public int NR_ORDEM { get; set; }
    
        public virtual ACAD_BLOCOS ACAD_BLOCOS { get; set; }
        public virtual ICollection<ACAD_USUARIOS_EXERCICIOS> ACAD_USUARIOS_EXERCICIOS { get; set; }
    }
}
