//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bloco
    {
        public Bloco()
        {
            this.Exercicio = new HashSet<Exercicio>();
            this.UsuarioBloco = new HashSet<UsuarioBloco>();
        }
    
        public int Id { get; set; }
        public int IdModulo { get; set; }
        public string Nome { get; set; }
        public string Pagina { get; set; }
        public int Ordem { get; set; }
    
        public virtual Modulo Modulo { get; set; }
        public virtual ICollection<Exercicio> Exercicio { get; set; }
        public virtual ICollection<UsuarioBloco> UsuarioBloco { get; set; }
    }
}
