//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CollegeEntities : DbContext
    {
        public CollegeEntities()
            : base("name=CollegeEntities")
        {
    		((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 180;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Academia> Academia { get; set; }
        public DbSet<Area> Area { get; set; }
        public DbSet<AreaCurso> AreaCurso { get; set; }
        public DbSet<Banner> Banner { get; set; }
        public DbSet<Bloco> Bloco { get; set; }
        public DbSet<Codigo> Codigo { get; set; }
        public DbSet<Curso> Curso { get; set; }
        public DbSet<Evento> Evento { get; set; }
        public DbSet<Exercicio> Exercicio { get; set; }
        public DbSet<Faq> Faq { get; set; }
        public DbSet<Matricula> Matricula { get; set; }
        public DbSet<Modulo> Modulo { get; set; }
        public DbSet<Questao> Questao { get; set; }
        public DbSet<Recurso> Recurso { get; set; }
        public DbSet<Testemunho> Testemunho { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<UsuarioBloco> UsuarioBloco { get; set; }
        public DbSet<UsuarioExercicio> UsuarioExercicio { get; set; }
        public DbSet<UsuarioProvaQuestao> UsuarioProvaQuestao { get; set; }
    }
}
