//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CollegeEntities : DbContext
    {
        public CollegeEntities()
            : base("name=CollegeEntities")
        {
    		((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 180;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACAD_ACADEMIAS> ACAD_ACADEMIAS { get; set; }
        public DbSet<ACAD_AREAS> ACAD_AREAS { get; set; }
        public DbSet<ACAD_AREAS_CURSOS> ACAD_AREAS_CURSOS { get; set; }
        public DbSet<ACAD_BANNERS> ACAD_BANNERS { get; set; }
        public DbSet<ACAD_BLOCOS> ACAD_BLOCOS { get; set; }
        public DbSet<ACAD_CODIGOS> ACAD_CODIGOS { get; set; }
        public DbSet<ACAD_CURSOS> ACAD_CURSOS { get; set; }
        public DbSet<ACAD_EVENTOS> ACAD_EVENTOS { get; set; }
        public DbSet<ACAD_EXERCICIOS> ACAD_EXERCICIOS { get; set; }
        public DbSet<ACAD_FAQS> ACAD_FAQS { get; set; }
        public DbSet<ACAD_MATRICULAS> ACAD_MATRICULAS { get; set; }
        public DbSet<ACAD_MODULOS> ACAD_MODULOS { get; set; }
        public DbSet<ACAD_QUESTOES> ACAD_QUESTOES { get; set; }
        public DbSet<ACAD_RECURSOS> ACAD_RECURSOS { get; set; }
        public DbSet<ACAD_TESTEMUNHOS> ACAD_TESTEMUNHOS { get; set; }
        public DbSet<ACAD_USUARIOS> ACAD_USUARIOS { get; set; }
        public DbSet<ACAD_USUARIOS_BLOCOS> ACAD_USUARIOS_BLOCOS { get; set; }
        public DbSet<ACAD_USUARIOS_EXERCICIOS> ACAD_USUARIOS_EXERCICIOS { get; set; }
        public DbSet<ACAD_USUARIOS_PROVAS_QUESTOES> ACAD_USUARIOS_PROVAS_QUESTOES { get; set; }
    }
}
