//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public Curso()
        {
            this.AreaCurso = new HashSet<AreaCurso>();
            this.Codigo = new HashSet<Codigo>();
            this.Matricula = new HashSet<Matricula>();
            this.Modulo = new HashSet<Modulo>();
        }
    
        public int Id { get; set; }
        public int IdAcademia { get; set; }
        public int IdProfessor { get; set; }
        public string Nome { get; set; }
        public string Resumo { get; set; }
        public string Descricao { get; set; }
        public string Email { get; set; }
        public string Moeda { get; set; }
        public decimal Valor { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public bool Ativo { get; set; }
        public int Ordem { get; set; }
    
        public virtual Academia Academia { get; set; }
        public virtual ICollection<AreaCurso> AreaCurso { get; set; }
        public virtual ICollection<Codigo> Codigo { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Matricula> Matricula { get; set; }
        public virtual ICollection<Modulo> Modulo { get; set; }
    }
}
