//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercicio
    {
        public Exercicio()
        {
            this.UsuarioExercicio = new HashSet<UsuarioExercicio>();
        }
    
        public int Id { get; set; }
        public int IdBloco { get; set; }
        public string Pergunta { get; set; }
        public string Gabarito { get; set; }
        public int Ordem { get; set; }
    
        public virtual Bloco Bloco { get; set; }
        public virtual ICollection<UsuarioExercicio> UsuarioExercicio { get; set; }
    }
}
