//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        public Matricula()
        {
            this.UsuarioExercicio = new HashSet<UsuarioExercicio>();
            this.UsuarioProvaQuestao = new HashSet<UsuarioProvaQuestao>();
        }
    
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public int IdCurso { get; set; }
        public string Codigo { get; set; }
        public string Transacao { get; set; }
        public System.DateTime DataCriacao { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<UsuarioExercicio> UsuarioExercicio { get; set; }
        public virtual ICollection<UsuarioProvaQuestao> UsuarioProvaQuestao { get; set; }
    }
}
