//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulo
    {
        public Modulo()
        {
            this.Bloco = new HashSet<Bloco>();
            this.Questao = new HashSet<Questao>();
            this.Recurso = new HashSet<Recurso>();
        }
    
        public int Id { get; set; }
        public int IdCurso { get; set; }
        public string Nome { get; set; }
        public string Pagina { get; set; }
        public int Ordem { get; set; }
    
        public virtual ICollection<Bloco> Bloco { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual ICollection<Questao> Questao { get; set; }
        public virtual ICollection<Recurso> Recurso { get; set; }
    }
}
