//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testemunho
    {
        public int Id { get; set; }
        public int IdAcademia { get; set; }
        public string Testemunho1 { get; set; }
        public string Autor { get; set; }
        public string Local { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public bool Ativo { get; set; }
    
        public virtual Academia Academia { get; set; }
    }
}
