//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioExercicio
    {
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public int IdExercicio { get; set; }
        public int IdMatricula { get; set; }
        public string Pergunta { get; set; }
        public string Resposta { get; set; }
        public string ObsCorrecao { get; set; }
        public System.DateTime DataCriacao { get; set; }
    
        public virtual Exercicio Exercicio { get; set; }
        public virtual Matricula Matricula { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
