//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Curso = new HashSet<Curso>();
            this.Matricula = new HashSet<Matricula>();
            this.UsuarioBloco = new HashSet<UsuarioBloco>();
            this.UsuarioExercicio = new HashSet<UsuarioExercicio>();
            this.UsuarioProvaQuestao = new HashSet<UsuarioProvaQuestao>();
        }
    
        public int Id { get; set; }
        public int IdAcademia { get; set; }
        public string Nome { get; set; }
        public string SobreNome { get; set; }
        public string NomeCompleto { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string Cpf { get; set; }
        public string Senha { get; set; }
        public string Ip { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public bool Ativo { get; set; }
    
        public virtual Academia Academia { get; set; }
        public virtual ICollection<Curso> Curso { get; set; }
        public virtual ICollection<Matricula> Matricula { get; set; }
        public virtual ICollection<UsuarioBloco> UsuarioBloco { get; set; }
        public virtual ICollection<UsuarioExercicio> UsuarioExercicio { get; set; }
        public virtual ICollection<UsuarioProvaQuestao> UsuarioProvaQuestao { get; set; }
    }
}
